<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>为什么代码没有按照编写执行顺序执行</title>
</head>

<body>

  <script>
    /**
      1.同步和异步
      程序在同步调用函数的时候,会立即执行操作并等待得到返回结果后再继续运行,也就是说同步执行是阻塞的;
      异步会将操作和结果在时间上分隔开来,在当下执行操作,在未来某个时刻返回结果,在这个等待返回结果的过程中,
      程序将继续执行后面的代码.也就是说异步执行是非阻塞的;

      异步操作都采用回调函数的形式.
      并非所有异步都回调,所有的回调函数不一定都是异步执行的.

      2.异步原理
      事件循环:
      对于大多数语言而言,实现异步会通过启动额外的进程,线程或协程来实现.
      为什么Javascript是单线程的还能实现异步呢?
      把一些操作交给了其他线程处理,然后采用以一种称之为"事件循环"(事件轮询)的机制来处理返回结果.

      那么这个事件队列里的事件是怎么来的呢？

      以 AJAX 请求为例，当我们发出一个 AJAX 请求时，浏览器会将请求任务分派给网络线程来进行处理，当对应的网络线程拿到返回的数据之后，就会把回调函数插入到事件队列中。

      setTimeout 和 setInterval 也是同样的道理，当我们执行 setTimeout 的时候并不是直接把回调函数放入事件队列中。它所做的是交给定时器线程来处理，当定时器到时后，再把回调函数放在事件队列中，这样，在未来的某轮 tick 中获取并执行这个回调函数。

      这么做有一个隐性的问题，如果事件队列中已经有其他事件，那么这个回调就会排队等待。

      所以说 setTimeout/setInterval 定时器的精度并不高。准确地说，它只能确保回调函数不会在指定的时间间隔之前运行，但可能会在那个时刻运行，也可能在那之后运行，这就要根据事件队列的状态而定。

      事件队列:
      在讲述 setTimeout/setInterval 原理的时候也暴露了事件队列的一个缺陷：事件队列按照先进先出的顺序执行，那么如果队列较长时，排在后面的事件即使较为“紧急”，也得需要等待前面的任务先执行完成。

      JavaScript 解决这个问题的思路就是：设置多个队列，按照优先级来执行。
      常见的异步函数优先级如下,从上到下优先级逐层降低:
      process.nextTick(Node.js) > 
      MutationObserver(浏览器)/promise.then(catch、finnally)>
      setImmediate(IE) > 
      setTimeout/setIntervalrequestAnimationFrame >
      其他 I/O 操作 / 浏览器 DOM 事件

      3.处理异步
      由于回调函数这种形式的代码可读性非常差，所以在编写代码的时候要尽量将回调形式转化成返回 Promise 对象的形式，一方面由于 ES6 标准下提供了原生 Promise 对象及方法，另一方面 Promise 的可操作性也更强，比如可以配合 async/await 关键字使用，也可以转换成 Observable 对象。所以越来越多的第三方库异步函数都开始返回 Promise 对象。

      异步串行:
      将异步转化为串行执行是非常常见的操作;

      异步并行:
      并行也是异步常用的场景，重点掌握下面 3 个静态函数。

      （1）Promise.all([promise1 ...... promiseN])

      调用函数 Promise.all 会返回一个新的 Promise 实例，该实例在参数内所有的 promise 都完成 (resolved) 时回调完成 (resolve)；如果参数中  promise 有一个失败（rejected），那么此实例返回第一个失败 promise 的结果。

      当执行的异步函数具有强一致性时可以使用它，比如要更新一个较大的表单数据，会发送多个请求分别更新不同的数据，如果一个请求更新失败则放弃本次提交。

      （2）Promise.allSettled([promise1......promiseN])

      调用函数 Promise.allsellted 会返回一个新的 Promise 实例，该实例会在所有给定的 promise 已经执行完成时返回一个对象数组，每个对象表示对应的 promise 结果。

      这个函数适用于需要并发执行多个异步函数，这些异步函数的执行结果相互独立。比如同时发送多个 AJAX 请求来分别更新多条数据。

      （3）Promise.race([promise1......promiseN])

      调用函数 Promise.race 会返回一个新的 promise 实例，一旦参数中的某个 promise 执行完成，新的 promise 实例就会返回对应 promise 的执行结果。

      这个函数会让多个并发函数产生“竞争”，从而挑选出最先执行完成的。比如尝试从多个网址加载图片资源。

      异常处理:
      Promise 有一个隐藏的“坑”，那就是内部的异常不能在外部通过 try/catch 所捕获，当内部发生异常时，会自动进入失败状态（rejected）。所以下面的代码是等价的：
      new Promise((resolve, reject) => {
        throw new Error(0) // 等价于  reject(new Error(0)) 
      })
      所以建议尽量使用 catch 子句而不是在 then 子句中捕获 Promise 异常，因为这样可以捕获 then 子句中的异常信息。

      补充：Promise 的局限性
      虽然 Promise 相对于回调具有明显的优势，但其仍然有一些局限性，至少有下面 2 个方面的问题。

      立即执行
      当一个 Promise 实例被创建时，内部的代码就会立即被执行，而且无法从外部停止。比如无法取消超时或消耗性能的异步调用，容易导致资源的浪费。

      单次执行
      Promise 处理的问题都是“一次性”的，因为一个 Promise 实例只能 resolve 或 reject 一次，所以面对某些需要持续响应的场景时就会变得力不从心。比如上传文件获取进度时，默认采用的就是通过事件监听的方式来实现。

      所以说 Promise 并不是万能的，全面了解其优缺点能帮助我们更好地使用 Promise。上述这些问题其实都有解决方案，比如使用 RxJS，期待你在工作中多思考、多积累，找到更多更好的解决方案。

      总结:

      这一课时涉及了 JavaScript 的核心特性——异步，先从异步概念说起，然后深入异步原理讲述了事件循环和事件队列，最后列举了 3 个常见异步场景的处理方法。异步属于笔试题必考的考点，比如任务队列部分，将 setTimeout/Promise/nextTick 这些异步函数和对象进行任意组合即可出题，所以一定要理解原理。

     */

    {
      // 同步和异步
      function syncAdd(a, b) {
        return a + b;
      }
      console.log(syncAdd(1, 2)); // 立即打印3

      function asyncAdd(a, b, cb) {
        setTimeout(function () {
          cb(a + b);
        }, 1000)
      }
      //asyncAdd(1, 2, console.log); // 1s后打印结果 3

      var a = {
        counter: {
          index: 1
        }
      }
      console.log(a);
      a.counter.index++;

      // 并非所有异步都回调,所有的回调函数不一定都是异步执行的.

    }

    {
      var eventLoop = []; // 事件队列，先进先出
      var event; // 事件执行成功的回调回调函数
      // while (true) {
      //   // 一次tick
      //   if (eventLoop.length > 0) {
      //     // 队列中取出回调函数
      //     event = eventLoop.shift();
      //     try {
      //       event();
      //     } catch (err) {
      //       reportError(err);
      //     }
      //   }
      // }

    }

    {
      console.log('----------------异步串行--------------');
      // asyncF1()
      //   .then(data => asyncF2(data))
      //   .then(() => {
      //     console.log(123)
      //   })
      //   .catch(e => console.error(e))

      // // 如果使用async/await可以摆脱链式调用,代码可读性更好;
      // (async function() {
      //   try {
      //     const data = await asyncF1()
      //     const result = await asyncF2()

      //   } catch(e) {
      //     console.error(e);
      //   }
      // })()
      var arr = [1, 2, 3, 4, 5]
      // arr.forEach((item, index) => {
      //   console.log(item, index);
      // })
      /*
          1、previousValue （上一次调用回调返回的值，或者是提供的初始值（initialValue））
          2、currentValue （数组中当前被处理的元素）
          3、index （当前元素在数组中的索引）
          4、array （调用 reduce 的数组）
      */
      var sum = arr.reduce((prev, cur, index, arr) => {
        console.log(prev, cur, index);
        return prev + cur
      })
      console.log(arr, sum);

      /*
        现在需要延迟打印数组 [1,2,3,4,5]，每一次打印的初始延迟为 1000ms，增长延迟为 500ms。
        0s:    1
        1s:    2
        2.5s: 3
        4.5s: 4
        7s:    5
      */

      const arrs = [1, 2, 3, 4, 5]
      // arrs.reduce(async(prs,cur,index) => {
      //   const t = await prs
      //   const time = index === 0 ? 0 : 1000 + (index - 1) * 500
      //   return new Promise((res) => {
      //     setTimeout(() => {
      //       res(time);
      //       console.log(cur);
      //     }, time)
      //   })   
      // }, Promise.resolve(0))

    }

    {
      console.log('---------------异步并行------------------');

    }

    {
      console.log('-----------------异常处理----------------');
      // Promise.resolve(1)
      // .then(data => {
      //   const arr = data.split('')
      //   console.log(arr);
      // }), error => { // 这里捕获不到
      //   console.log('error');
      // }
      Promise.resolve(1)
      .then(data => {
        const arr = data.split('')
        console.log(arr);
      }) 
      .catch(err => { // 这里可以捕获
        console.log(err);
      })












    }





  </script>



</body>

</html>